- name: Read the ansible var from anotehr file
  hosts: localhost
  vars_file:
  - local_varibles.yaml
  tasks:
  - name: pring the var from another file
    ansible.builtin.debug:
      msg: hi {{NAME}} thanks for learning{{COURSE}}