- name: This example contains the different types of var usage 
  hosts: localhost
  become: yes
  vars_prompt:
    - name: Uid
      prompt: please enter name
      private: false
    - name: Plc
      prompt: please enter place
      private: false
  vars_files:
    - local_varibles.yaml
  #Playlevel vars declaration
  vars:
  - username: Sudheer
  - place: kadapa
  tasks:
  - name: printing the vars from the play level
    ansible.builtin.debug:
      msg: Hi {{username}} and he is from {{place}}

  - name: Overriding the vars in child level/task level
    vars:
    - username: sudheerPagadala
    ansible.builtin.debug:
      msg: Hi {{username}} and he is from the {{place}}

  - name: Taking from the local files
    ansible.builtin.debug:
      msg: hi {{Local_username}}

  - name: Taking from the promt
    ansible.builtin.debug:
      msg: Hi {{Uid}}



    
