- name: This ecample contains the different types of var usage 
  hosts: localhost
  become: yes
  #Playlevel vars declaration
  vars:
    username: Sudheer
    place: kadapa
  tasks:
  - name: printing the vars from the play level
    ansible.builtin.debug:
      msg: Hi {{username}} and he is from {{place}}
  - name: Overriding the vars in child level/task level
    vars:
    - username: sudheerPagadala
    ansible.builtin.debug:
      msg: Hi {{username}} and he is from the {{place}}
  - name: taking the vars from the files
    vars_files: 
    - local_varibles.yaml
    ansible.builtin.debug:
      msg: Hi {{username}} and he is in {{place}}
  - name: Taking the username from promt
    vars_prompt:
    - name: USERNAME
      prompt: please enter username
      private : false
    - name: place
      prompt: please enter your place
      private: false
    ansible.builtin.debug:
      msg: Hi {{USERNAME}} and he is from the {{place}}



    
